name: Infrastructure CI Pipeline
on:
  push:
    branches: [ main, develop ]
    paths:
      - 'infrastructure/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'infrastructure/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6
        
    - name: Terraform Format
      run: |
        cd infrastructure/deployment/terraform
        terraform fmt -check
        
    - name: Terraform Init
      run: |
        cd infrastructure/deployment/terraform
        terraform init -backend=false
        
    - name: Terraform Validate
      run: |
        cd infrastructure/deployment/terraform
        terraform validate
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd infrastructure
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run tests
      run: |
        cd infrastructure
        pytest --cov=. --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./infrastructure/coverage.xml
        fail_ci_if_error: true
